### PR TITLE
Add claims and mild cleanup

### PR DESCRIPTION
**Pull request by W4ngatang**
tl;dr (too long; didn't review):

I'm running ELMo reruns and LM reruns of most things except wiki and reddit classification; CCG; non-GLUE MTL.

I'm waiting on a s2s PR to launch those jobs.

### CODE REVIEW

**Comment by W4ngatang** [comment]
Not quite yet.

**Comment by sleepinyourhat** [comment]
@W4ngatang  Merge?

**Comment by sleepinyourhat** [comment]
Nudge.

**Comment by sleepinyourhat** [comment]
Another nudge.

**Comment by W4ngatang** [comment]
no more nudges

**Comment by sleepinyourhat** [comment]
🎉

**Pull request merged**
