### PR TITLE
Pytorch and AllenNLP upgrade

### PR DESCRIPTION
**Pull request by pruksmhc**
Upgrading to 1.0.0 and 0.8.1
Refer to #442  for notes. 
The last_dim_softmax in AllenNLP was merged into masked_softmax (See this PR: https://github.com/allenai/allennlp/pull/1687/files).

### CODE REVIEW

**Comment by pruksmhc** [comment]
Confirmed

**Comment by sleepinyourhat** [comment]
Hrm. We had been using a 100 character line limit. Did it look like there
were any more configurable style checkers?

**Comment by iftenney** [comment]
This is causing a lot of problems with running in Docker, largely because of conflicts between required packages for AllenNLP 0.8.1 and other packages that we're using.

I'm trying to resolve this, but we really need to run a more comprehensive test suite before merging breaking changes like this, especially when there are still experiments in progress (edge probing for ICLR camera-ready).

**Comment by iftenney** [comment]
Can someone verify that PyTorch checkpoints are recoverable (and consistent) across versions? I noticed while working on something else that they're implemented as pickles: https://pytorch.org/docs/stable/torch.html?highlight=torch%20load#torch.load

**Pull request merged**
